version: "3"
services:
  api:
    image: node:16
    container_name: api
    working_dir: /app
    command: npm run server
    ports:
      - "3000:3000"
    volumes:
      - "./server/:/app"
  web:
    image: node:16
    container_name: web
    working_dir: /src
    command: npm start
    ports:
      - "5173:5173"
    volumes:
      - "./client/:/src"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: youssef
      MONGO_INITDB_ROOT_PASSWORD: youssef
    volumes:
      - db-data:/data/db
volumes:
  db-data: {}
